### ISSUE TITLE
Install failed using Linuxbrew: No such file or directory - output/share/xmake/xmake

### ISSUE THREAD

**Issue by guyskk** [tboox/xmake#49]
I install xmake using https://github.com/Linuxbrew/brew on Arch Linux, here is the error messages:

```
$ brew install --debug xmake
Updating Homebrew...
/home/guyskk/.linuxbrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /home/guyskk/.linuxbrew/Library/Taps/homebrew/homebrew-core/Formula/xmake.rb
/home/guyskk/.linuxbrew/Library/Homebrew/build.rb (Formulary::FromPathLoader): loading /home/guyskk/.linuxbrew/Library/Taps/homebrew/homebrew-core/Formula/xmake.rb
==> Downloading https://github.com/waruqi/xmake/archive/v2.0.5.tar.gz
Already downloaded: /home/guyskk/.cache/Homebrew/xmake-2.0.5.tar.gz
==> ./install output
/home/guyskk/.linuxbrew/Library/Homebrew/debrew.rb:11:in `raise'
Errno::ENOENT: No such file or directory - output/share/xmake/xmake
1. raise
2. ignore
3. backtrace
4. irb
5. shell
Choose an action: 1
==> Kept temporary files
Temporary files retained at /tmp/xmake-20170116-21478-1qsehl5
Error: No such file or directory - output/share/xmake/xmake
/home/guyskk/.linuxbrew/Library/Homebrew/debrew.rb:11:in `raise'
/home/guyskk/.linuxbrew/Library/Homebrew/extend/pathname.rb:90:in `install_p'
/home/guyskk/.linuxbrew/Library/Homebrew/extend/pathname.rb:84:in `block in install'
/home/guyskk/.linuxbrew/Library/Homebrew/extend/pathname.rb:65:in `each'
/home/guyskk/.linuxbrew/Library/Homebrew/extend/pathname.rb:65:in `install'
/home/guyskk/.linuxbrew/Library/Taps/homebrew/homebrew-core/Formula/xmake.rb:18:in `install'
/home/guyskk/.linuxbrew/Library/Homebrew/debrew.rb:22:in `block in install'
/home/guyskk/.linuxbrew/Library/Homebrew/debrew.rb:97:in `debrew'
/home/guyskk/.linuxbrew/Library/Homebrew/debrew.rb:22:in `install'
/home/guyskk/.linuxbrew/Library/Homebrew/build.rb:137:in `block in install'
/home/guyskk/.linuxbrew/Library/Homebrew/formula.rb:1118:in `block in brew'
/home/guyskk/.linuxbrew/Library/Homebrew/formula.rb:1884:in `block in stage'
/home/guyskk/.linuxbrew/Library/Homebrew/resource.rb:98:in `block in unpack'
/home/guyskk/.linuxbrew/Library/Homebrew/extend/fileutils.rb:14:in `block in mktemp'
/home/guyskk/.linuxbrew/Library/Homebrew/extend/fileutils.rb:74:in `block in run'
/home/guyskk/.linuxbrew/Library/Homebrew/extend/fileutils.rb:74:in `chdir'
/home/guyskk/.linuxbrew/Library/Homebrew/extend/fileutils.rb:74:in `run'
/home/guyskk/.linuxbrew/Library/Homebrew/extend/fileutils.rb:13:in `mktemp'
/home/guyskk/.linuxbrew/Library/Homebrew/resource.rb:94:in `unpack'
/home/guyskk/.linuxbrew/Library/Homebrew/resource.rb:86:in `stage'
/home/guyskk/.linuxbrew/Library/Homebrew/formula.rb:1871:in `stage'
/home/guyskk/.linuxbrew/Library/Homebrew/formula.rb:1113:in `brew'
/home/guyskk/.linuxbrew/Library/Homebrew/build.rb:112:in `install'
/home/guyskk/.linuxbrew/Library/Homebrew/build.rb:189:in `<main>'
```

**Comment by waruqi** [comment]
Please attempt to run 'brew update' first, or clone the dev branch of xmake to install it.

```
$ git clone https://github.com/tboox/xmake.git -b dev
$ cd ./xmake
$ sudo ./install
```

Thanks!

**Comment by guyskk** [comment]
@waruqi clone the dev branch of xmake to install works, master branch also works well, brew install still fail.

**Comment by waruqi** [comment]
Ok, you can use the master version now and I will update new version to linuxbrew in future.
